### ISSUE TITLE
[Telegram] funziona ancora dopo dismissione ifttt?

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/RSSdisegniLeggeAssembleaRegionaleSiciliana#5]
Ciao! Domanda (forse stupida) il canale https://t.me/ars_unofficial funziona anche dopo la dismissione di ifttt? È gestito da un altro servizio? Grazie 

cc @aborruso

**Comment by aborruso** [comment]
Sì, funzionerà ancora!

**Comment by dennisangemi** [comment]
Grazie @aborruso <3
